export const items = [
  {
    _id: "651e5a7cf1b7f3d9b77a68eb",
    name: "Game Management",
    code: 101,
    iconClass: "icon-settings",
    status: true,
    completed: false,
    allCompleted: false,
    subModule: [
      {
        subname: "Table View & Creation",
        code: 102,
        route: "/gameManagementHome/table-view",
        iconClass: "icon-puzzle",
        status: true,
        completed: false,
      },
    ],
    __v: 0,
  },
  {
    _id: "651e5a7cf1b7f3d9b77a68f1",
    name: "User Management",
    code: 1201,
    iconClass: "icon-settings",
    status: true,
    completed: false,
    allCompleted: false,
    subModule: [
      {
        subname: "List Players",
        code: 1206,
        route: "/userManagement/list-players",
        iconClass: "icon-puzzle",
        status: true,
        completed: false,
      },
      {
        subname: "Daily LogIn Report",
        code: 1216,
        route: "/userManagement/daily-login-report",
        iconClass: "icon-puzzle",
        status: true,
        completed: false,
      },
    ],
    __v: 0,
  },
  {
    _id: "651e5a7cf1b7f3d9b77a68fd",
    name: "Broadcast Management",
    code: 2401,
    iconClass: "icon-settings",
    status: true,
    completed: false,
    allCompleted: false,
    subModule: [
      {
        subname: "Broadcast to game",
        code: 2403,
        route: "/broadcastManagement/broadcast-to-game",
        iconClass: "icon-puzzle",
        status: true,
        completed: false,
      },
    ],
    __v: 0,
  },
  {
    _id: "651e5a7cf1b7f3d9b77a6905",
    name: "Version & Maintenance",
    code: 2301,
    iconClass: "icon-settings",
    status: true,
    completed: false,
    allCompleted: false,
    subModule: [
      {
        subname: "Create New Version",
        code: 2303,
        route: "versionMaintainence/create-new-version",
        iconClass: "icon-puzzle",
        status: true,
        completed: false,
      },
      {
        subname: "List Versions",
        code: 2304,
        route: "versionMaintainence/list-versions",
        iconClass: "icon-puzzle",
        status: true,
        completed: false,
      },
    ],
    __v: 0,
  },
];
